fail_fast: true
repos:
- repo: local
  hooks:
  - id: format
    name: Format
    stages: [commit]
    language: system
    entry: pipenv run format
    types: [python]
  - id: lint
    name: Lint
    stages: [commit]
    language: system
    entry: pipenv run lint
    types: [python]
  - id: test
    name: Test
    stages: [commit]
    language: system
    entry: pipenv run test
    types: [python]
